version: "3"
services:
  item-service-container:
    image: item-service-image
    ports:
      - "9001:9001"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqlcontainer:3306/item_service_db?useSSL=false
    networks:
      - item-service-mysql
    depends_on:
      - mysqlcontainer

  mysqlcontainer:
    image: mysql:latest
    networks:
      - item-service-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=item_service_db
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234

networks:
  item-service-mysql: