spring:
  application:
    name: sales-order-service
  datasource:
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/sales_order_service_db
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: '9003'
logging:
  level:
    org:
      hibernate:
        SQL: INFO
